server:
  port: 8888

spring:
  application:
    name: dynamic-threadpool-zookeeper-example

  dynamic:
    thread-pool:
      config-file-type: properties
      zookeeper:
        zk-connect-str: 127.0.0.1:2181
        config-version: 1.0.0
        root-node: /configserver/userproject
        node: zookeeper-demo

#logging:
#  level:
#    root: DEBUG