server:
  port: 8088
  servlet:
    context-path: /example

spring:
  profiles:
    active: dev

  application:
    name: price

  dynamic:
    thread-pool:
      server-addr: http://localhost:6691
      namespace: zg
      item-id: price
      username: admin
      password: 123456
